safi:
  jwt:
    expiration: 86400000
    secret: safi-project

#Database configuration
server:
  port: 8080
  servlet:
    contextPath : /safi-finance/api
spring:
  datasource:
    url:
    username:
    password:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
##Jpa configuration
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddlAuto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    verify:
      email: https://safifront.azurewebsites.net/validate/
    sender:
      address: pedro_pdantas@hotmail.com
      name: SAFI

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true