
safi:
  jwt:
    expiration: 86400000
    secret: safi-project

#Database configuration
server:
  servlet:
    context-path: /safi-finance/api
spring:
  datasource:
    url: jdbc:sqlserver://safidb.database.windows.net;databaseName=SafiDB
    username: SafiAdmin
    password: Cederj123
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
##Jpa configuration
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: pedroppd90@gmail.com
    password: Thugstools@11515
    verify:
      email: http://localhost:8080/safi-finance/api/email/verify
    subject:
      content: Por favor, verifique seu cadastro.
    recipient:
      address: pedro_pdantas@hotmail.com
    sender:
      address: pedro_pdantas@hotmail.com
      name: SAFI
    content:
      path: ./src/main/java/br/com/safi/mail/MailContent.txt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true