
safi:
  jwt:
    expiration: 86400000
    secret: safi-project

#Database configuration
server:
  servlet:
    contextPath : /safi-finance/api
spring:
  datasource:
    url: jdbc:sqlserver://safidb.database.windows.net;databaseName=SafiDB
    username: SafiAdmin
    password: Cederj123
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
##Jpa configuration
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddlAuto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: safifinance2022@gmail.com
    password: safi@1234
    verify:
      email: https://safibackend.azurewebsites.net/safi-finance/api/email/verify
    subject:
      content: Por favor, verifique seu cadastro.
    recipient:
      address: pedro_pdantas@hotmail.com
    sender:
      address: pedro_pdantas@hotmail.com
      name: SAFI

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true