#Database configuration
spring:
  datasource:
    url: jdbc:sqlserver://safidb.database.windows.net;databaseName=SafiDB
    username: SafiAdmin
    password: Cederj123
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
##Jpa configuration
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto:  update

  safi:
    jwt:
      expiration: 86400000
      secret: safi-project

  mail:
    host: smtp.gmail.com
    port: 587
    username: pedro_pdantas@hotmail.com
    password: 123456
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



 ## spring.mail.host=smtp.gmail.com
 ## spring.mail.port=587
 ## spring.mail.username=your_email_address
 ## spring.mail.password=your_email_password
 ## spring.mail.properties.mail.smtp.auth=true
 ## spring.mail.properties.mail.smtp.starttls.enable=true